# Project-wide Gradle settings.
# Enables modern AndroidX libraries required by Jetpack Compose
android.useAndroidX=true

# JVM memory allocation for Gradle Daemon in Ubuntu MATE
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style
kotlin.code.style=official

# Faster build optimizations
android.nonTransitiveRClass=true
