import { WorkoutPlan } from '../types';

/**
 * Generates valid C source code struct initialization for the workout plan
 */
export function exportPlanToCHeader(plan: WorkoutPlan): string {
  const safeVarName = plan.name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '') || 'custom_plan';

  let c = `/* Generated by Interval Timer C & Web Suite */\n`;
  c += `/* Plan: ${plan.name} */\n\n`;
  c += `#ifndef PRESET_${safeVarName.toUpperCase()}_H\n`;
  c += `#define PRESET_${safeVarName.toUpperCase()}_H\n\n`;
  c += `#include "interval_timer.h"\n\n`;
  c += `static const WorkoutPlan ${safeVarName} = {\n`;
  c += `    .name = "${plan.name.replace(/"/g, '\\"')}",\n`;
  c += `    .prep_seconds = ${plan.prepSeconds},\n`;
  c += `    .cycles = ${plan.cycles},\n`;
  c += `    .cycle_rest_seconds = ${plan.cycleRestSeconds},\n`;
  c += `    .num_sets = ${plan.sets.length},\n`;
  c += `    .sets = {\n`;

  plan.sets.forEach((set, index) => {
    c += `        /* Set ${index + 1} */\n`;
    c += `        {\n`;
    c += `            .name = "${set.name.replace(/"/g, '\\"')}",\n`;
    c += `            .work_seconds = ${set.workSeconds},\n`;
    c += `            .rest_seconds = ${set.restSeconds},\n`;
    c += `            .sound_work_freq = ${set.workSoundFreq || 880},\n`;
    c += `            .sound_rest_freq = ${set.restSoundFreq || 440}\n`;
    c += `        }${index < plan.sets.length - 1 ? ',' : ''}\n`;
  });

  c += `    }\n`;
  c += `};\n\n`;
  c += `#endif /* PRESET_${safeVarName.toUpperCase()}_H */\n`;
  return c;
}
