import { WorkoutPlan } from '../types';

export const DEFAULT_WORKOUT_PRESETS: WorkoutPlan[] = [
  {
    id: 'tabata-classic',
    name: 'Табата Классик (20/10)',
    description: 'Высокоинтенсивный интервальный тренинг: 8 раундов по 20 сек работы и 10 сек отдыха.',
    prepSeconds: 5,
    cycles: 1,
    cycleRestSeconds: 0,
    isCustom: false,
    sets: Array.from({ length: 8 }).map((_, i) => ({
      id: `tabata-set-${i + 1}`,
      name: `Раунд ${i + 1}`,
      workSeconds: 20,
      restSeconds: 10,
    })),
  },
  {
    id: 'hiit-pyramid',
    name: 'HIIT Пирамида (Сложные сеты)',
    description: 'Сложный цикл с переменной длительностью работы и отдыха для каждого сета.',
    prepSeconds: 10,
    cycles: 2,
    cycleRestSeconds: 60,
    isCustom: false,
    sets: [
      { id: 'pyr-1', name: 'Ступень 1: Разгон', workSeconds: 30, restSeconds: 15 },
      { id: 'pyr-2', name: 'Ступень 2: Нагрузка', workSeconds: 45, restSeconds: 20 },
      { id: 'pyr-3', name: 'Ступень 3: ПИК', workSeconds: 60, restSeconds: 30 },
      { id: 'pyr-4', name: 'Ступень 4: Снижение', workSeconds: 45, restSeconds: 20 },
      { id: 'pyr-5', name: 'Ступень 5: Спринт-финиш', workSeconds: 30, restSeconds: 15 },
    ],
  },
  {
    id: 'boxing-rounds',
    name: 'Боксёрские Раунды (3 мин)',
    description: '5 классических раундов по 3 минуты работы с 1 минутой отдыха между раундами.',
    prepSeconds: 10,
    cycles: 1,
    cycleRestSeconds: 0,
    isCustom: false,
    sets: Array.from({ length: 5 }).map((_, i) => ({
      id: `boxing-set-${i + 1}`,
      name: `Бокс Раунд ${i + 1}`,
      workSeconds: 180,
      restSeconds: 60,
    })),
  },
  {
    id: 'sprint-intervals',
    name: 'Интервальный Бег / Спринт',
    description: 'Взрывные ускорения 30 секунд с активным шагом 60 секунд. 2 цикла с отдыхом 2 минуты.',
    prepSeconds: 15,
    cycles: 2,
    cycleRestSeconds: 120,
    isCustom: false,
    sets: Array.from({ length: 4 }).map((_, i) => ({
      id: `sprint-set-${i + 1}`,
      name: `Спринт ${i + 1}`,
      workSeconds: 30,
      restSeconds: 60,
    })),
  },
  {
    id: 'core-abs-circuit',
    name: 'Круговая для Пресса (Core)',
    description: '4 упражнения на пресс по 45 секунд работы и 15 секунд перехода. 3 круга.',
    prepSeconds: 8,
    cycles: 3,
    cycleRestSeconds: 45,
    isCustom: false,
    sets: [
      { id: 'core-1', name: 'Скручивания', workSeconds: 45, restSeconds: 15 },
      { id: 'core-2', name: 'Велосипед', workSeconds: 45, restSeconds: 15 },
      { id: 'core-3', name: 'Подъем ног в висе/лежа', workSeconds: 45, restSeconds: 15 },
      { id: 'core-4', name: 'Статическая планка', workSeconds: 45, restSeconds: 15 },
    ],
  },
];
